### PR TITLE
fix: use Mongo everywhere (sync start-database script with Payload config)

### PR DESCRIPTION
**Pull request by mickaeltr**
The `payload.config.ts` uses Mongo by default, but the `start-database.sh` starts a PostgreSQL instance. This sets MongoDB everywhere.

### CODE REVIEW

**Comment by xprnio** [comment]
Doesn't Payload ask whether to use Postgres or Mongo when generating the project?
If so, wouldn't it make more sense to switch between Mongo and Postgres files?

**Comment by mickaeltr** [comment]
> Doesn't Payload ask whether to use Postgres or Mongo when generating the project? If so, wouldn't it make more sense to switch between Mongo and Postgres files?

Unless I've misunderstood the purpose of this demo repository, I expect the instructions in the README to work, but currently they don't because of a mix of postgres and mongo.

Please see:
- https://github.com/payloadcms/payload-3.0-demo/blob/main/README.md#using-this-repo
- https://github.com/payloadcms/payload-3.0-demo/blob/main/payload.config.ts#L80

**Comment by xprnio** [comment]
Right, my bad. I must've confused the CLI and this demo repo.
But in any case, would it perhaps be better than to rename `start-database.sh` to `start-postgres.sh` and create an additional `start-mongo.sh` since Postgres requires more "configuration" than Mongo by default? I think that this would make setting up the database easier for the user regardless of whether they prefer Mongo or Postgres (speaking as a Postgres enjoyer).

**Comment by xprnio** [comment]
I just feel that a big part of the 3.0 update is support for Postgres (or virtually any Drizzle-compatible database), and dropping the database setup script entirely might cause confusion or friction for those wanting to make use of it

**Comment by mickaeltr** [comment]
Thank you for your feedback. I am a new Payload CMS user who was unable to run the demo with the instructions given. I therefore submit the smallest changes that allowed me to run this demo successfully.

**Comment by denolfe** [comment]
Mongo is pretty straight-forward to connect to. We'll keep the PG script.

**Pull request closed without merging**
